app = "sssmusic-telegram-bot"
primary_region = "ams"

[build]
  command = "pip install -r requirements.txt"

[env]
  BOT_TOKEN = "7841283903:AAGbo9X-OSoewgOsgJn_CoWBKBaPwQe117o"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
