services:
  - type: web
    name: telegram-youtube-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 7841283903:AAGbo9X-OSoewgOsgJn_CoWBKBaPwQe117o
